# -*- coding: utf-8 -*-
"""mlpart1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-X7AQ-HGoBymugTsHY_JnxyJCv7arX6z
"""

import numpy as np
from sklearn.linear_model import LinearRegression

x = [[2], [4], [6], [8], [10], [12], [14], [16], [18], [20]]
y = [1, 4, 7, 10, 13, 16, 19, 21, 24, 27]

regr = LinearRegression().fit(x, y)
regr.score(x, y)

predict = np.array([[2]])

print ("prediksi")
print("input = ", predict)
print("output = ", regr.predict(predict))